# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aulas/Descargas/4.practicafinal/sol-letras/juego_letras/misol

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aulas/Descargas/4.practicafinal/sol-letras/juego_letras/misol

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aulas/Descargas/4.practicafinal/sol-letras/juego_letras/misol/CMakeFiles /home/aulas/Descargas/4.practicafinal/sol-letras/juego_letras/misol/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aulas/Descargas/4.practicafinal/sol-letras/juego_letras/misol/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named zip

# Build rule for target.
zip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zip
.PHONY : zip

# fast build rule for target.
zip/fast:
	$(MAKE) -f CMakeFiles/zip.dir/build.make CMakeFiles/zip.dir/build
.PHONY : zip/fast

#=============================================================================
# Target rules for targets named cifras

# Build rule for target.
cifras: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cifras
.PHONY : cifras

# fast build rule for target.
cifras/fast:
	$(MAKE) -f CMakeFiles/cifras.dir/build.make CMakeFiles/cifras.dir/build
.PHONY : cifras/fast

#=============================================================================
# Target rules for targets named mrproper

# Build rule for target.
mrproper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mrproper
.PHONY : mrproper

# fast build rule for target.
mrproper/fast:
	$(MAKE) -f CMakeFiles/mrproper.dir/build.make CMakeFiles/mrproper.dir/build
.PHONY : mrproper/fast

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) -f CMakeFiles/doc_doxygen.dir/build.make CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

#=============================================================================
# Target rules for targets named cantidad_letras

# Build rule for target.
cantidad_letras: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cantidad_letras
.PHONY : cantidad_letras

# fast build rule for target.
cantidad_letras/fast:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/build
.PHONY : cantidad_letras/fast

#=============================================================================
# Target rules for targets named letras

# Build rule for target.
letras: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 letras
.PHONY : letras

# fast build rule for target.
letras/fast:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/build
.PHONY : letras/fast

#=============================================================================
# Target rules for targets named testdiccionario

# Build rule for target.
testdiccionario: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testdiccionario
.PHONY : testdiccionario

# fast build rule for target.
testdiccionario/fast:
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/build
.PHONY : testdiccionario/fast

src/cantidad_letras.o: src/cantidad_letras.cpp.o

.PHONY : src/cantidad_letras.o

# target to build an object file
src/cantidad_letras.cpp.o:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/cantidad_letras.cpp.o
.PHONY : src/cantidad_letras.cpp.o

src/cantidad_letras.i: src/cantidad_letras.cpp.i

.PHONY : src/cantidad_letras.i

# target to preprocess a source file
src/cantidad_letras.cpp.i:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/cantidad_letras.cpp.i
.PHONY : src/cantidad_letras.cpp.i

src/cantidad_letras.s: src/cantidad_letras.cpp.s

.PHONY : src/cantidad_letras.s

# target to generate assembly for a file
src/cantidad_letras.cpp.s:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/cantidad_letras.cpp.s
.PHONY : src/cantidad_letras.cpp.s

src/cifras.o: src/cifras.cpp.o

.PHONY : src/cifras.o

# target to build an object file
src/cifras.cpp.o:
	$(MAKE) -f CMakeFiles/cifras.dir/build.make CMakeFiles/cifras.dir/src/cifras.cpp.o
.PHONY : src/cifras.cpp.o

src/cifras.i: src/cifras.cpp.i

.PHONY : src/cifras.i

# target to preprocess a source file
src/cifras.cpp.i:
	$(MAKE) -f CMakeFiles/cifras.dir/build.make CMakeFiles/cifras.dir/src/cifras.cpp.i
.PHONY : src/cifras.cpp.i

src/cifras.s: src/cifras.cpp.s

.PHONY : src/cifras.s

# target to generate assembly for a file
src/cifras.cpp.s:
	$(MAKE) -f CMakeFiles/cifras.dir/build.make CMakeFiles/cifras.dir/src/cifras.cpp.s
.PHONY : src/cifras.cpp.s

src/dictionary.o: src/dictionary.cpp.o

.PHONY : src/dictionary.o

# target to build an object file
src/dictionary.cpp.o:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/dictionary.cpp.o
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/dictionary.cpp.o
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/src/dictionary.cpp.o
.PHONY : src/dictionary.cpp.o

src/dictionary.i: src/dictionary.cpp.i

.PHONY : src/dictionary.i

# target to preprocess a source file
src/dictionary.cpp.i:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/dictionary.cpp.i
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/dictionary.cpp.i
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/src/dictionary.cpp.i
.PHONY : src/dictionary.cpp.i

src/dictionary.s: src/dictionary.cpp.s

.PHONY : src/dictionary.s

# target to generate assembly for a file
src/dictionary.cpp.s:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/dictionary.cpp.s
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/dictionary.cpp.s
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/src/dictionary.cpp.s
.PHONY : src/dictionary.cpp.s

src/letras.o: src/letras.cpp.o

.PHONY : src/letras.o

# target to build an object file
src/letras.cpp.o:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letras.cpp.o
.PHONY : src/letras.cpp.o

src/letras.i: src/letras.cpp.i

.PHONY : src/letras.i

# target to preprocess a source file
src/letras.cpp.i:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letras.cpp.i
.PHONY : src/letras.cpp.i

src/letras.s: src/letras.cpp.s

.PHONY : src/letras.s

# target to generate assembly for a file
src/letras.cpp.s:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letras.cpp.s
.PHONY : src/letras.cpp.s

src/letters_bag.o: src/letters_bag.cpp.o

.PHONY : src/letters_bag.o

# target to build an object file
src/letters_bag.cpp.o:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letters_bag.cpp.o
.PHONY : src/letters_bag.cpp.o

src/letters_bag.i: src/letters_bag.cpp.i

.PHONY : src/letters_bag.i

# target to preprocess a source file
src/letters_bag.cpp.i:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letters_bag.cpp.i
.PHONY : src/letters_bag.cpp.i

src/letters_bag.s: src/letters_bag.cpp.s

.PHONY : src/letters_bag.s

# target to generate assembly for a file
src/letters_bag.cpp.s:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letters_bag.cpp.s
.PHONY : src/letters_bag.cpp.s

src/letters_set.o: src/letters_set.cpp.o

.PHONY : src/letters_set.o

# target to build an object file
src/letters_set.cpp.o:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/letters_set.cpp.o
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letters_set.cpp.o
.PHONY : src/letters_set.cpp.o

src/letters_set.i: src/letters_set.cpp.i

.PHONY : src/letters_set.i

# target to preprocess a source file
src/letters_set.cpp.i:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/letters_set.cpp.i
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letters_set.cpp.i
.PHONY : src/letters_set.cpp.i

src/letters_set.s: src/letters_set.cpp.s

.PHONY : src/letters_set.s

# target to generate assembly for a file
src/letters_set.cpp.s:
	$(MAKE) -f CMakeFiles/cantidad_letras.dir/build.make CMakeFiles/cantidad_letras.dir/src/letters_set.cpp.s
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/letters_set.cpp.s
.PHONY : src/letters_set.cpp.s

src/solver.o: src/solver.cpp.o

.PHONY : src/solver.o

# target to build an object file
src/solver.cpp.o:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/solver.cpp.o
.PHONY : src/solver.cpp.o

src/solver.i: src/solver.cpp.i

.PHONY : src/solver.i

# target to preprocess a source file
src/solver.cpp.i:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/solver.cpp.i
.PHONY : src/solver.cpp.i

src/solver.s: src/solver.cpp.s

.PHONY : src/solver.s

# target to generate assembly for a file
src/solver.cpp.s:
	$(MAKE) -f CMakeFiles/letras.dir/build.make CMakeFiles/letras.dir/src/solver.cpp.s
.PHONY : src/solver.cpp.s

src/testdiccionario.o: src/testdiccionario.cpp.o

.PHONY : src/testdiccionario.o

# target to build an object file
src/testdiccionario.cpp.o:
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/src/testdiccionario.cpp.o
.PHONY : src/testdiccionario.cpp.o

src/testdiccionario.i: src/testdiccionario.cpp.i

.PHONY : src/testdiccionario.i

# target to preprocess a source file
src/testdiccionario.cpp.i:
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/src/testdiccionario.cpp.i
.PHONY : src/testdiccionario.cpp.i

src/testdiccionario.s: src/testdiccionario.cpp.s

.PHONY : src/testdiccionario.s

# target to generate assembly for a file
src/testdiccionario.cpp.s:
	$(MAKE) -f CMakeFiles/testdiccionario.dir/build.make CMakeFiles/testdiccionario.dir/src/testdiccionario.cpp.s
.PHONY : src/testdiccionario.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... zip"
	@echo "... cifras"
	@echo "... mrproper"
	@echo "... doc_doxygen"
	@echo "... cantidad_letras"
	@echo "... edit_cache"
	@echo "... letras"
	@echo "... testdiccionario"
	@echo "... src/cantidad_letras.o"
	@echo "... src/cantidad_letras.i"
	@echo "... src/cantidad_letras.s"
	@echo "... src/cifras.o"
	@echo "... src/cifras.i"
	@echo "... src/cifras.s"
	@echo "... src/dictionary.o"
	@echo "... src/dictionary.i"
	@echo "... src/dictionary.s"
	@echo "... src/letras.o"
	@echo "... src/letras.i"
	@echo "... src/letras.s"
	@echo "... src/letters_bag.o"
	@echo "... src/letters_bag.i"
	@echo "... src/letters_bag.s"
	@echo "... src/letters_set.o"
	@echo "... src/letters_set.i"
	@echo "... src/letters_set.s"
	@echo "... src/solver.o"
	@echo "... src/solver.i"
	@echo "... src/solver.s"
	@echo "... src/testdiccionario.o"
	@echo "... src/testdiccionario.i"
	@echo "... src/testdiccionario.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

