package GUI;
import civitas.Jugador;

public class JugadorPanel extends javax.swing.JPanel {
    private Jugador jugador;

    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    void setJugador(Jugador j){
        this.jugador=j;
        Nombre.setText(jugador.getNombre());
        Saldo.setText(Float.toString(jugador.getSaldo()));
        Nombre.repaint();
        Saldo.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Saldo = new javax.swing.JTextField();
        Especulador = new javax.swing.JTextField();

        jLabel1.setText("Nombre");
        add(jLabel1);

        jLabel2.setText("Saldo");
        add(jLabel2);

        jLabel3.setText("¿Especulador?");
        add(jLabel3);

        Nombre.setEditable(false);
        Nombre.setText("jTextField1");
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        add(Nombre);

        Saldo.setEditable(false);
        Saldo.setText("jTextField2");
        Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoActionPerformed(evt);
            }
        });
        add(Saldo);

        Especulador.setEditable(false);
        Especulador.setText("jTextField3");
        add(Especulador);
    }// </editor-fold>//GEN-END:initComponents

    private void SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Especulador;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Saldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
